//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SİTESİ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisim
    {
        public int iletisimID { get; set; }
        public int kayitID { get; set; }
        public string tur { get; set; }
        public string bilgi { get; set; }
    
        public virtual kayit_table kayit_table { get; set; }
    }
}
