//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SİTESİ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kayit_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kayit_table()
        {
            this.iletisim = new HashSet<iletisim>();
        }
    
        public int kayitID { get; set; }
        public string adiniz { get; set; }
        public string soyadiniz { get; set; }
        public string TCKN { get; set; }
        public string adres { get; set; }
        public string hasar_bilgisi { get; set; }
        public string beklentiniz_nedir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iletisim> iletisim { get; set; }
    }
}
